# Generated by Django 5.2.16 on 2026-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
